---
title: "My intro"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "HuiHsuan Chan"
date: "9/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About Me

I am Huihsuan Chan from Taiwan. I did my undergraduate in Pharmacy in Taipei Medical University. However, being a pharmacist is so boring. I decided to started my career in pharmaceutical industry. During past four years in pharma industry, I learned how to license drugs, and I understood how the healthcare market works. In order to catch up the big data trend, pharma companies started to promote and mange their customers through digital stuff. I realized that now is a big data time, I have to learn something. Then, I started to learn Python when the Pandemic began. I love it, and I want to learn other similar language to handle data. So, I am here.


## Three fun facts about me

1. I like scuba and free diving.
2. I do not eat breakfast.
3. Because my careless, my family and I missed an flight in Guam during the Chinese New Year.

## Intresting youtuber 
They are Taiwanese but grew up in the US. 
They did lots of fun and meaningful things to encourage people to step out of their comfy zone.
https://www.youtube.com/results?search_query=thedodomen


